# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cars' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxAlamofire+ObjectMapper'
  pod 'AlamofireObjectMapper'
  pod 'RxCocoa',    '~> 4.0'
  pod 'JGProgressHUD'
  pod 'MJSnackBar'
  pod 'PopItUp'
  pod 'Hue'
  pod 'Localize' , '~> 2.0.5'
  pod 'SwiftEventBus'
  pod 'Luminous'

  # Pods for Cars

  target 'CarsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
